FROM pestun/debian.10.opam.2.1.2.ocaml.4.13.1.coq.8.11.dev

RUN curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o \
    Miniconda3-latest-Linux-x86_64.sh && sh Miniconda3-latest-Linux-x86_64.sh -b -f

ENV HOME="/home/coq"
ENV CONDA_EXE="${HOME}/miniconda3/bin/conda"

RUN $CONDA_EXE create -n python3.9 python=3.9 -y
ENV CONDA_PREFIX="${HOME}/miniconda3/envs/python3.9"
ENV CONDA_PYTHON_EXE="${HOME}/miniconda3/bin/python"
RUN echo 'PATH=$CONDA_PREFIX/bin:$PATH' >> .profile




